### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by michalss** [2sic/oqtane-theme-2shine-bs5#3]
Is this fully supported on latest oqtane will be this supported always ?

**Comment by iJungleboy** [comment]
Hi @michalss 

This works on the latest Oqtane and we'll continue to develop / enhance it. 

Do note that this is still an early release, as we plan to dramatically improve cre8magic (https://cre8magic.blazor-cms.org/) and then change how it's distributed, because cre8magic should become an own nuget package. 

As of now there are some docs but there is probably quite a learning curve to get started with making amazing looking sites ;)

Note that you got a quick answer now, but I'll be away next week so don't expect any kind of live-support ;)

**Comment by michalss** [comment]
Thank you. I would like to make a nice looking website, unfortunately Oqtane is not theme user friendly enough for most of us.. So this could be a game changer... :) thx for answer

**Comment by michalss** [comment]
@iJungleboy  it would help if you could release some working complete example in the meantime... :)

**Comment by iJungleboy** [comment]
@michalss actually it works right from the start ;) so you're good to go.

But the goal is that you do 99% in configuration only (no need to change Razor files) - so that's where you need to get familiar with cre8magic ;)

**Comment by michalss** [comment]
im gonna try it today
